### ISSUE TITLE
Add autofix feature on autofixable rules like graphql-schema/type-fields-sorted-alphabetically

### ISSUE THREAD

**Issue by Mrtblg** [joshuaNathaniel/eslint-plugin-graphql-schema#12]
It would be great to have an autofix feature on rules like `graphql-schema/type-fields-sorted-alphabetically`

**Comment by joshuaNathaniel** [comment]
Yup, I absolutely agree. I can look into it. I have a couple babies so it's been a bit hard to find the time but I'll make some time.

**Comment by joshuaNathaniel** [comment]
Sorry for the delay. I'm officially starting work on this today.
