### ISSUE TITLE
Add the ability to parse gql strings inside .js files

### ISSUE THREAD

**Issue by Mrtblg** [joshuaNathaniel/eslint-plugin-graphql-schema#13]
On client side requests are most of the time writtent in `.js` files inside a :

```javascript
const myQuery = gql`

`
```

which allows for multiple requests in the same file.

It would be great to support this as this project here does : https://github.com/apollographql/eslint-plugin-graphql

**Comment by joshuaNathaniel** [comment]
@Mrtblg I need to estimate the effort on this. I'm currently using a custom parser for graphql. Not sure if I have the time. If you really need it and have the time and expertise to get this done then feel free to contribute.

**Comment by joshuaNathaniel** [comment]
After giving this some thought and research, I have determined your request to be outside the scope of this plugin.
