### ISSUE TITLE
Be more specific on the line not well placed for `graphql-schema/type-fields-sorted-alphabetically`

### ISSUE THREAD

**Issue by Mrtblg** [joshuaNathaniel/eslint-plugin-graphql-schema#14]
When one line is not well sorted all the block is marked as invalid.

It would be great to mark as invalid only the lines that are not at the right place.

I have no clue how to do it but i know that most of sorting librairies do it well

**Comment by Mrtblg** [comment]
PS : thank you for your work. It is well integrated with eslint.

Personaly i'm just interested in the `graphql-schema/type-fields-sorted-alphabetically` functionnality and modulo the 3 issues I opened I think your plugin is production ready !

**Comment by joshuaNathaniel** [comment]
I'm starting the work on this.

**Comment by joshuaNathaniel** [comment]
v2.0.1 will now report object type fields out of order.
